First commit
Aritra8438/Job-applications-manager pull request #13
Opened 2023-06-03 04:22 UTC by alphawolf07

2023-06-03 05:51 UTC, Aritra8438 commented
Great PR!
Things I want to mention:
- There are changes in `requirements.txt`. Run `pip freeze > requirements.txt` in the root directory and commit it as well. 
- For now, let's keep it to sqlite3. We will host `postgres database` at **Neon** later.

It seems like, you are working on forked repo. No problem with that, but you have the access to the main repo as well.

2023-06-03 05:53 UTC, Aritra8438 commented on backend/settings.py
>      }
Let's keep sqlite3 for now.

2023-06-03 05:54 UTC, alphawolf07 commented
Okay I'll do the requirements.txt part. As for the postgres, I'm doing it
in my branch for my convenience but I'll change it to sqlite before
committing.

On Sat, 3 Jun, 2023, 11:21 am Aritra Majumder, ***@***.***>
wrote:

> Great PR!
> Things I want to mention:
>
>    - There are changes in requirements.txt. Run pip freeze >
>    requirements.txt in the root directory and commit it as well.
>    - For now, let's keep it to sqlite3. We will host postgres database at
>    *Neon* later.
>
> It seems like, you are working on forked repo. No problem with that, but
> you have the access to the main repo as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aritra8438/Job-applications-manager/pull/13#issuecomment-1574688633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASBUNTG5MVYLPN4YPXTZ6BLXJLGFFANCNFSM6AAAAAAYZBK5KU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-03 05:56 UTC, Aritra8438 requested changes
Commit `requirements.txt`.

2023-06-04 20:24 UTC, Aritra8438 approved these changes

2023-06-04 20:24 UTC, merged